### PR TITLE
Add COPASI to list of languages

### PR DESCRIPTION
**Pull request by fbergmann**
It would be nice if COPASI could be added to the list of language urns.

### CODE REVIEW

**Comment by luciansmith** [comment]
This is a list of model languages, not simulation programs.  No other SBML simulator is listed, you'll note.

**Review by nickerso — APPROVED** [review]
I think the COPASI model format is widely enough used that it is fine to add it to the list. Seems to fit with others that are already on the list that are tool specific modelling formats and the given link takes the reader to the file format description not the tool.

**Comment by luciansmith** [comment]
All those simulators have their own format.  Jonathan Karr spent a lot of time (for some reason) getting SED-ML to be compatible with all sorts of one-off non-standards-compliant formats, and the results are here.

As far as I know, COPASI doesn't have one-off non-standards-compliant format that is used in SED-ML; it uses SBML instead, as is right and proper.

**Comment by fbergmann** [comment]
COPASI has its own file format (linked in the PR), not all of it is compatible with SBML. It would help us to serialize some of it using this submission. I'm not sure where the problem would be with just listing it on this page.

**Comment by luciansmith** [comment]
Oh!  Well, if you have your own standards-incompatible format, let's add it to the list, then!

**Pull request merged**
