### PR TITLE
Updating editors listing

### PR DESCRIPTION
**Pull request by nickerso**
and seeing if a PR will trigger the website to update. This `editors.yml` file seemed out of date with what is currently displayed on sed-ml.org so not completely sure this is the right way to edit the content...

### CODE REVIEW

**Comment by eagmon** [comment]
apparently the website is using the `about.html` file for the editors page, I'm not sure what the yaml is doing. added the change to this PR

**Comment by eagmon** [comment]
@nickerso @luciansmith CI is failing on two tests. Do you recognize these errors? https://github.com/SED-ML/sed-ml.github.io/actions/runs/5057620424/jobs/9076606190.

**Comment by luciansmith** [comment]
I just turned on the 'test examples SED-ML' file again because it had timed out (no activity within 60 days), thinking it might be necessary to get the changes committed to the page.  Nope!  It just showed a new error!  One that's probably been hidden for a year and a half or so.  I'll look into it; in the worst case, I'll just turn off the tests.

**Review by luciansmith — APPROVED** [review]

**Comment by luciansmith** [comment]
There, got it working!

However, the link to Eran's picture is broken, so I'll see if I can fix that next.

**Pull request merged**
