### PR TITLE
Update editors information.

### PR DESCRIPTION
**Pull request by luciansmith**

### CODE REVIEW

**Comment by luciansmith** [comment]
I think this is how this works?

**Review by nickerso — APPROVED** [review]

**Comment by luciansmith** [comment]
@nickerso Is there some other action we have to run to get this to take?  The actual 'about' page seems to not have updated.

**Comment by nickerso** [comment]
might need @matthiaskoenig to help here - I thought it all built and updated with github actions...

**Comment by fbergmann** [comment]
I think it might be enough to just re-enable and running the CI workflow (that was automatically disabled by github for lack of activity).

**Comment by nickerso** [comment]
thanks @fbergmann - that did the trick. And found an error :) Just trying to get things working in #79 now...

**Pull request merged**
